SUPABASE_URL="https://kstbdlykpegrzaefjnoi.supabase.co"

SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzdGJkbHlrcGVncnphZWZqbm9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwODUxMDUsImV4cCI6MjA5MjY2MTEwNX0.fdkf7t5B42s1vbYWuEO1PQCn_c_n-tldF3VXxZaLKwA"